TrainingArguments:
  num_train_epochs: 0.5
  warmup_steps: 50
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 5000
  gradient_accumulation_steps: 2

