artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://data.deepai.org/conll2003.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.txt", "test.txt", "valid.txt"]
  DATA_DIR: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion 
  tokenizer_name: bert-base-cased  
  max_length: 512

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/ner_processed_dataset
  model_ckpt: distilbert-base-cased
  num_train_epochs: 3
  learning_rate: 2e-5
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/ner_processed_dataset
  model_path: artifacts/model_trainer/ner-model
  tokenizer_path: artifacts/model_trainer/ner-model
  metric_file_name: artifacts/model_evaluation/ner_metrics.csv